apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
spec:
  selector:
    app: redis-cluster
  ports:
  - name: client
    port: 6379
  - name: gossip
    port: 16379
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis01
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis01
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis02
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis02
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis03
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis03
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis04
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis04
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis05
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis05
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis06
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /redis06
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  selector:
    matchLabels:
      app: redis-cluster
  serviceName: redis-cluster-service
  replicas: 6
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis
        image: redis:5.0.1-alpine
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: 'data'
          mountPath: '/data'
          readOnly: false
        ports:
        - name: client
          containerPort: 6379
        - name: gossip
          containerPort: 16379
        env:
        - name: 'POD_IP'
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - name: 'conf'
        configMap:
          name: redis-cluster-configmap
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
